/**
 * Axiom Forge - Deployment Service
 * 
 * Handles deployment to GitHub and Vercel
 */

import { Octokit } from '@octokit/rest';
import { exec } from 'child_process';
import { promisify } from 'util';
import path from 'path';
import fs from 'fs/promises';

const execAsync = promisify(exec);

// ==================== DEPLOYMENT SERVICE CLASS ====================
export class DeploymentService {
  constructor(securityManager) {
    this.securityManager = securityManager;
    this.octokit = null;
    this.vercelToken = null;
  }

  // ==================== PRIVATE METHODS ====================

  async _getGitHubToken() {
    const result = await this.securityManager.getToken('github-token');
    if (!result) {
      throw new DeploymentError('GITHUB_TOKEN_MISSING', 'GitHub token not configured');
    }
    return result;
  }

  async _getVercelToken() {
    const result = await this.securityManager.getToken('vercel-token');
    if (!result) {
      throw new DeploymentError('VERCEL_TOKEN_MISSING', 'Vercel token not configured');
    }
    return result;
  }

  async _initOctokit() {
    if (!this.octokit) {
      const token = await this._getGitHubToken();
      this.octokit = new Octokit({ auth: token });
    }
    return this.octokit;
  }

  async _initVercel() {
    if (!this.vercelToken) {
      this.vercelToken = await this._getVercelToken();
    }
    return this.vercelToken;
  }

  async _executeGitCommand(cwd, command) {
    try {
      const { stdout, stderr } = await execAsync(command, { cwd });
      return { stdout: stdout.trim(), stderr: stderr.trim() };
    } catch (error) {
      throw new DeploymentError('GIT_COMMAND_FAILED', error.message);
    }
  }

  // ==================== GITHUB OPERATIONS ====================

  /**
   * Push project to GitHub
   */
  async pushToGitHub(projectId, projectPath, onProgress = () => {}) {
    onProgress({ message: 'Initializing GitHub client...', progress: 0 });
    
    const octokit = await this._initOctokit();
    
    // Get user info
    onProgress({ message: 'Getting user info...', progress: 10 });
    const { data: user } = await octokit.rest.users.getAuthenticated();
    const username = user.login;
    
    // Generate repo name
    const repoName = `axiom-forge-${projectId}`;
    
    onProgress({ message: 'Creating repository...', progress: 20 });
    
    try {
      // Create the repository
      await octokit.rest.repos.createForAuthenticatedUser({
        name: repoName,
        description: `Generated by Axiom Forge - ${projectId}`,
        private: false,
        auto_init: false
      });
    } catch (error) {
      if (error.status === 422) {
        // Repo might already exist, try to use it
        onProgress({ message: 'Repository exists, using existing...', progress: 25 });
      } else {
        throw new DeploymentError('GITHUB_CREATE_REPO_FAILED', error.message);
      }
    }
    
    onProgress({ message: 'Initializing git repository...', progress: 30 });
    
    // Initialize git and push
    const token = await this._getGitHubToken();
    const remoteUrl = `https://${username}:${token}@github.com/${username}/${repoName}.git`;
    
    try {
      // Check if git is already initialized
      const gitDir = path.join(projectPath, '.git');
      try {
        await fs.access(gitDir);
      } catch {
        // Initialize git
        await this._executeGitCommand(projectPath, 'git init');
      }
      
      onProgress({ message: 'Configuring git...', progress: 40 });
      
      // Configure git
      await this._executeGitCommand(projectPath, 'git config user.email "axiom-forge@localhost"');
      await this._executeGitCommand(projectPath, 'git config user.name "Axiom Forge"');
      
      onProgress({ message: 'Adding files...', progress: 50 });
      
      // Add all files
      await this._executeGitCommand(projectPath, 'git add .');
      
      onProgress({ message: 'Committing...', progress: 60 });
      
      // Commit
      try {
        await this._executeGitCommand(projectPath, 'git commit -m "Initial commit from Axiom Forge"');
      } catch (error) {
        // Might be nothing to commit
        onProgress({ message: 'No changes to commit...', progress: 65 });
      }
      
      onProgress({ message: 'Setting remote...', progress: 70 });
      
      // Set remote
      try {
        await this._executeGitCommand(projectPath, `git remote add origin ${remoteUrl}`);
      } catch {
        // Remote might already exist
        await this._executeGitCommand(projectPath, `git remote set-url origin ${remoteUrl}`);
      }
      
      onProgress({ message: 'Pushing to GitHub...', progress: 80 });
      
      // Push
      await this._executeGitCommand(projectPath, 'git push -u origin main --force');
      
      onProgress({ message: 'GitHub push complete!', progress: 100 });
      
      return {
        success: true,
        repoName,
        repoUrl: `https://github.com/${username}/${repoName}`,
        username
      };
      
    } catch (error) {
      throw new DeploymentError('GITHUB_PUSH_FAILED', error.message);
    }
  }

  /**
   * Delete GitHub repository
   */
  async deleteGitHubRepo(repoName) {
    const octokit = await this._initOctokit();
    const { data: user } = await octokit.rest.users.getAuthenticated();
    
    try {
      await octokit.rest.repos.delete({
        owner: user.login,
        repo: repoName
      });
      return { success: true };
    } catch (error) {
      throw new DeploymentError('GITHUB_DELETE_FAILED', error.message);
    }
  }

  // ==================== VERCEL OPERATIONS ====================

  /**
   * Deploy to Vercel
   */
  async deployToVercel(projectId, repoName, onProgress = () => {}) {
    onProgress({ message: 'Initializing Vercel...', progress: 0 });
    
    const token = await this._initVercel();
    
    // Get GitHub info
    const octokit = await this._initOctokit();
    const { data: user } = await octokit.rest.users.getAuthenticated();
    const githubRepo = `${user.login}/${repoName}`;
    
    onProgress({ message: 'Creating Vercel project...', progress: 20 });
    
    try {
      // Create project
      const createResponse = await fetch('https://api.vercel.com/v9/projects', {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${token}`,
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          name: `axiom-forge-${projectId}`,
          framework: null, // Auto-detect
          gitRepository: {
            type: 'github',
            repo: githubRepo
          }
        })
      });
      
      if (!createResponse.ok && createResponse.status !== 409) {
        const error = await createResponse.text();
        throw new DeploymentError('VERCEL_CREATE_FAILED', error);
      }
      
      const project = createResponse.ok ? await createResponse.json() : null;
      const projectName = project?.name || `axiom-forge-${projectId}`;
      
      onProgress({ message: 'Triggering deployment...', progress: 50 });
      
      // Trigger deployment
      const deployResponse = await fetch('https://api.vercel.com/v13/deployments', {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${token}`,
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          name: projectName,
          gitSource: {
            type: 'github',
            repo: githubRepo,
            ref: 'main'
          }
        })
      });
      
      if (!deployResponse.ok) {
        const error = await deployResponse.text();
        throw new DeploymentError('VERCEL_DEPLOY_FAILED', error);
      }
      
      const deployment = await deployResponse.json();
      
      onProgress({ message: 'Waiting for deployment...', progress: 70 });
      
      // Poll for deployment status
      let status = deployment.readyState;
      const deploymentId = deployment.id;
      const maxAttempts = 30;
      let attempts = 0;
      
      while (status !== 'READY' && status !== 'ERROR' && attempts < maxAttempts) {
        await new Promise(resolve => setTimeout(resolve, 2000));
        
        const statusResponse = await fetch(`https://api.vercel.com/v13/deployments/${deploymentId}`, {
          headers: { 'Authorization': `Bearer ${token}` }
        });
        
        if (statusResponse.ok) {
          const statusData = await statusResponse.json();
          status = statusData.readyState;
          
          const progress = 70 + ((attempts / maxAttempts) * 25);
          onProgress({ message: `Deployment status: ${status}...`, progress });
        }
        
        attempts++;
      }
      
      if (status === 'ERROR') {
        throw new DeploymentError('VERCEL_DEPLOY_ERROR', 'Deployment failed');
      }
      
      onProgress({ message: 'Deployment complete!', progress: 100 });
      
      return {
        success: true,
        url: deployment.url ? `https://${deployment.url}` : null,
        id: deploymentId,
        status
      };
      
    } catch (error) {
      if (error instanceof DeploymentError) throw error;
      throw new DeploymentError('VERCEL_DEPLOY_FAILED', error.message);
    }
  }

  /**
   * Get Vercel deployments
   */
  async getVercelDeployments(projectId) {
    const token = await this._initVercel();
    
    try {
      const response = await fetch(`https://api.vercel.com/v6/deployments?projectId=${projectId}`, {
        headers: { 'Authorization': `Bearer ${token}` }
      });
      
      if (!response.ok) {
        throw new DeploymentError('VERCEL_LIST_FAILED', 'Failed to fetch deployments');
      }
      
      return await response.json();
    } catch (error) {
      throw new DeploymentError('VERCEL_LIST_FAILED', error.message);
    }
  }

  /**
   * Delete Vercel project
   */
  async deleteVercelProject(projectId) {
    const token = await this._initVercel();
    
    try {
      const response = await fetch(`https://api.vercel.com/v9/projects/${projectId}`, {
        method: 'DELETE',
        headers: { 'Authorization': `Bearer ${token}` }
      });
      
      if (!response.ok && response.status !== 404) {
        throw new DeploymentError('VERCEL_DELETE_FAILED', 'Failed to delete project');
      }
      
      return { success: true };
    } catch (error) {
      throw new DeploymentError('VERCEL_DELETE_FAILED', error.message);
    }
  }

  // ==================== VERIFICATION ====================

  /**
   * Verify deployment is accessible
   */
  async verifyDeployment(url) {
    try {
      const response = await fetch(url, {
        method: 'HEAD',
        timeout: 10000
      });
      
      return response.ok;
    } catch (error) {
      return false;
    }
  }

  // ==================== UTILITY ====================

  /**
   * Test GitHub connection
   */
  async testGitHubConnection() {
    try {
      const octokit = await this._initOctokit();
      const { data: user } = await octokit.rest.users.getAuthenticated();
      
      return {
        success: true,
        username: user.login,
        message: `Connected as ${user.login}`
      };
    } catch (error) {
      return {
        success: false,
        message: error.message
      };
    }
  }

  /**
   * Test Vercel connection
   */
  async testVercelConnection() {
    try {
      const token = await this._initVercel();
      
      const response = await fetch('https://api.vercel.com/v2/user', {
        headers: { 'Authorization': `Bearer ${token}` }
      });
      
      if (!response.ok) {
        throw new Error('Invalid token');
      }
      
      const data = await response.json();
      
      return {
        success: true,
        username: data.user?.username || 'Unknown',
        message: `Connected as ${data.user?.username || 'Unknown'}`
      };
    } catch (error) {
      return {
        success: false,
        message: error.message
      };
    }
  }
}

// ==================== CUSTOM ERROR CLASS ====================
export class DeploymentError extends Error {
  constructor(code, message) {
    super(message);
    this.name = 'DeploymentError';
    this.code = code;
  }
}

export default DeploymentService;
